### ISSUE TITLE
Stop word in 100 frequent words result

### ISSUE THREAD

**Issue by nmortell** [metten0/moby_dick_word_frequency_exercise#2]
After clicking the "100 Frequent Words" the scrollable list contains a result for "\"i". "I" is a character to remove according to the stop words text file.

Also "it's" is included in the result set the stop word text includes 'its'. Could possibly consider this an error in the format of the stop words file. When comparing for removal, standardize the text, all lowercase remove apostrophes etc.

**Comment by metten0** [comment]
Thank you for the feedback. Line 61 of `readfile.js` was written to handle this (` return word.replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g, "").toLowerCase();`). Clearly, this is not completely doing the trick. I intend to research why the "i" made it through and reach out to a senior dev if I cannot locate the issue.

 During pairing yesterday, there was some conversation about the cost/benefit related to removing apostrophes. Based on my takeaway from the conversation, I elected to leave them in. Please advise with regard to the client's preference or give direction.

Much thanks,

Jason

**Comment by nmortell** [comment]
The regex used here does not include a capture for `\"` so double quotations wont be removed.

**Comment by nmortell** [comment]
when using standardization often time needs to be spent looking at your source of truth, In this case your stop words txt file. If a desire exists to retain the grammatically correct punctuation in the result on the screen then. Simply create a standardizing function for comparison so that you end up with something like the following:
```
// assuming item is a string for brevity
// the following is just a bland comparator for example's sake
for(var item in list) {
	var standardizedStr = standardize(item)
	if(stopwords.contains(standardizedStr)){
			// dont add item
	} else {
			// add item
	}
}

private string standardize(string original)
{
	// remove grammatical punctiuation, just apostrophe as far i as know
	// lowercase all characters
}
```
The item added above would still have its apostrophe so picky english teachers don't pick apart an incorrect implementation of a contraction.

**Comment by metten0** [comment]
I just figured out the "i" problem while waiting for the oven to preheat. The first word of dialogue is always going to defeat the stop word list as it occurs after a quotation mark with no spaces in between.. I will continue to ponder and attempt to apply the solution proposed above.

**Comment by metten0** [comment]
Removed apostrophes and quotes from the novel with regex.

**Comment by metten0** [comment]
I have put a great deal of thought into this and reached out to a senior developer or two. My current plan is to use regex to remove quotation marks. This should remove all instances of a stop word sneaking through the filter when it immediately follows a quotation mark _(_ex__ "I am having a nice day"). There remains a minuscule chance that the numbers will be skewed a bit in edge cases where quotes are used for something other than dialogue, but there cases are statistically rare enough that I am prepared to deem them immaterial.

As far as apostrophes, are concerned...the current plan is to create a separate github branch and write some logic that will grab each instance where an apostrophe exists, drop everything to the right until it reaches a space, and analyze everything to the left until it reaches a space. If the data to the left is a stop word, it will be removed. If the data to the left is not a stopword, it will be counted. 

Of course, there are edge cases here as well. Ideally, the contraction _day's_ (_ex_ This day's going to be a long one) should be considered differently than the possessive day's  (_ex_ The day's schedule includes lots of Javascript). I am of the opinion that such an analysis would require entirely new, cost prohibitive software, and is likely statistically immaterial as well. Therefore, I do not intend to pursue this edge case at this time unless directed otherwise.

**Comment by metten0** [comment]
Completed as described above. Will close this issue as no objection was heard. However, please feel free to reopen if this solution is less than sufficient.

Thanks,

Jason
